[package]
name = "nashar_gah"
version = "0.1.0"
edition = "2021"

crate-type = ["lib"]

[dependencies]
anyhow = "1.0.86"
http = "1.1.0"
httparse = "1.9.4"
tokio = { version = "1.39.3", features = ["full"] }
meta_tags = { path = "./meta_tags" }